server:
  port: 8060

spring:
  application:
    name: apiGateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
         - id: lessonService
           uri: lb://lessonService
           predicates:
             - Path=/lesson/**
         - id: studentService
           uri: lb://studentService
           predicates:
             - Path=/student/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
